### ISSUE TITLE
Handle re-authentication every some weeks

### ISSUE THREAD

**Issue by 0rTiN** [Thomas55555/husqvarna_automower#101]
Hey,
is it possible to handle somehow the recurring re-authentication. Its hard to say how often it is necessary and its not a bit deal, but maybe there is an elegant way to handle it.

Bye,
Daniel

**Comment by simontegelid** [comment]
I have seen this too. It seems like the refreshing of the access token using the refresh token fails with return code 400 from time to time. It should do this if the system has been offline (and the refresh token not used) for 10 days, but it seems like the API is responding with 400 occasionally even when using refresh tokens that should be valid. In this case, the only way to get back to a working state is to login again using username and password. We can work around this if we store the username and password in the config entry for the integration.

**Comment by Thomas55555** [comment]
Since 2021.8.0 I didn't had any issues we re-authentication. But since I'm testing the websocket it happens again. Maybe we should store username and password again to make it more stable. It's not my preferred way, but when the token refreshing is not working properly, I don't see an alternative. And other integrations are doing it, too.

**Comment by simontegelid** [comment]
Aha! Then It's my fault :) I'll add a callback to aioautomower that's fired on token refresh which can be used in this integration to update the entry.

**Comment by simontegelid** [comment]
This should be resolved in https://github.com/Thomas55555/husqvarna_automower/pull/115 Let's observe this for a while and see if it reappears.
