### ISSUE TITLE
Dashboard request

### ISSUE THREAD

**Issue by RodEzIO** [Thomas55555/husqvarna_automower#356]
Hello, could you please also share the dashboard code ? I am referring to the one visible in your screenshot.
Thanks

**Comment by Thomas55555** [comment]
This is just the standard integration page.

**Comment by mulcmu** [comment]
The automation shown on the screenshot was custom from my setup.  I didn't like that the mower would go out and cut for only a few minutes near the end of the scheduled time and return with nearly a full battery.  This automation uses an input helper to specify the minimum number of minutes the mower should have left in the schedule to cut, otherwise it waits until the next scheduled start.  The schedule end time then becomes the latest time that you want to mower to still be cutting.

```
alias: Automower minimum runtime
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.automower_next_start
    from: unknown
condition:
  - condition: template
    value_template: |2-
        {% set seconds_nextstart_to_scheduleend =
         as_timestamp(state_attr('calendar.automower', 'end_time'))|default(0) - 
         as_timestamp(states('sensor.automower_next_start'))|default(0)     | float %}

        {% if seconds_nextstart_to_scheduleend < (states('input_number.minimum_cut_time') | float) * 60  %}

        {{true}}

        {% else %}

        {{false}}

        {% endif %}
action:
  - service: husqvarna_automower.custom_command
    data:
      command_type: actions
      json_string: |-
        {
         "data": {"type": "ParkUntilNextSchedule"}
        }
    target:
      entity_id: vacuum.automower
mode: single
```

**Comment by Thomas55555** [comment]
For further questions use the discussion tab
