### ISSUE TITLE
Only north-south bound maps supported

### ISSUE THREAD

**Issue by Din-BH** [Thomas55555/husqvarna_automower#462]
**Prerequirements**
[X] I have connected my mower(s) to the Automower Connect App
[X] I have connected my Husqvarna developers account to the Authentication API
[X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
The Map camera does not seem to work correctly when the direction of the map image is not north/south rotated. According to the service description, indicating the top-left and bottom-right coordinates should be suficient, but when you try to do that with an image that is rotated from best user angle rather than north-is-up, then the map drawings are incorrect.

Also, the image gets truncated in reality unless the ratio is as expected by the camera, which means that the coordinates need to be given after the truncation is known. It would be good to add the required ratio to the documentation.

**Expected behavior**
The direction of the map image should not matter.

**Screenshots**
This works OK since north is up
![v10gras446x320north](https://github.com/Thomas55555/husqvarna_automower/assets/58572670/b8839de0-69c9-492a-acfd-66d07c53da47)

This does not, the picture is orientated as best suited from end user perspective
![v10gras446x320](https://github.com/Thomas55555/husqvarna_automower/assets/58572670/7ce1abe2-9568-4073-ab75-eb9c195cd876)

**Additional context**
Thanks for great work on the integration!!

**Comment by prairiesnpr** [comment]
We don't resize the image, HA will resize the image, based on screen size, but that's after we have generated the mower position and track.  Are you seeing errors in the image when using a North oriented image?

**Comment by Din-BH** [comment]
With north oriented image it works fine from aspect of plotting movements as far as I can tell. Are you sure HA resizes based on screen size? I am seeing the same picture on all devices - cropped the same way. Phone, tablet, PC.

**Comment by prairiesnpr** [comment]
I reworked the scale logic so that we now find the hypotenuse in meters and pixels, calculating a ratio from that, then for every point we find the distance in meters and a bearing from the center of the image and then scale it.  This allows for applying a rotation correction. The rotation can be set through the config options. In addition, we also now resize the image to the size HA requests.  I'll be running this for a few weeks to make sure that I didn't miss anything, but you are welcome to test it and provide feedback. https://github.com/prairiesnpr/husqvarna_automower
