### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [Thomas55555/husqvarna_automower#5]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by Thomas55555** [comment]
Thank you for the offer. Some automation would be helpful, I think.

**Comment by KTibow** [comment]
Do you want me to send in just hassfest and HACS, with flake8, or with flake8 and automatic formatting?

**Comment by Thomas55555** [comment]
Puh...I don't know. This is all new to me. I think I can run flake8 in my virtual environment before pushing to github. So I don't have an idea, if this would make sense in Github. Maybe it's easier if there is an automatic formatting, so I don't have to do it by myself. What do you think?
For hassfest I found an instruction, so I could do this on my own.
Maybe the HACS would be helpful? Right now I have problems with a PR there.
What I really need is something, which makes me a description for a release, so that I have all the changes documented in there.

**Comment by KTibow** [comment]
Try this out 😃
https://github.com/release-drafter/release-drafter

**Comment by Thomas55555** [comment]
Thank you
