### ISSUE TITLE
"Override schedule" option

### ISSUE THREAD

**Issue by xens** [Thomas55555/husqvarna_automower#58]
Hi @Thomas55555 thanks for this HA integration, it just worked out of the box on my HA deployment (2021.4.6) with version husqvarna_automower v.2021.4.2.

I have a quite unusual setup and I wanted to have you advice. Currently I haven't configured and schedules for my Mower so it cannot start by itself, the reason is that we have some small children around and we want to control when we launch the mower , and for that we're using the Husqvarna app and we "override" the schedule for a certain amount of time. The problem that with the current HA integration by sending the "start" command the mower won't start because there's no corresponding schedule so only stop, pause or return-home is working.

According to Husqvarna APIs (https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/swagger)  there's a way in the "Planner" object to send a "override" action "FORCE_MOW" so I guess that we could adapt the husqvarna_automower code to also handle schedules overrides. Now I'm wondering how it'd be integrated inside HA, could we define a new action / button to trig it ? Or should we add an option in the husqwarna_automower configuration where we could modify the behavior of the start button ? (overriding instead of starting).

Let me know what you think, happy to contribute if I can.

Romain

**Comment by Thomas55555** [comment]
Hi, an additional button is not possible, because as far as I understood it, you always need a duration time for the override and you can't do that in a simple way with a button. Also this is not fitting to the home assistant vacuum platform.
But there are to other solutions:
1. You can set your planner to mow 24/7, and stop it, when the children are out with the pause/stop/home button. And resume with the start button.
2. I just added a custom services to send a park or start command with a duration time. You can use the service to make your own buttons in home assistant. So you can force mowing. You can test it by downloading the husqvarna automower beta 2021.5.0b1. But you have to upgrade to at least home assistant 2021.5.0b0 first, to get it working.

**Comment by xens** [comment]
Hi @Thomas55555 option 1 work perfectly thanks a lot for that ! I'll test option 2 as soon as I'll be on the 2021.5.0 and I'll let you know !
